
-- Create NAICS Codes Table
CREATE TABLE naics_codes (
    naics_code INT PRIMARY KEY,
    description TEXT NOT NULL
);

-- Create Technologies Table
CREATE TABLE technologies (
    id SERIAL PRIMARY KEY,
    category TEXT NOT NULL,
    subcategory TEXT NOT NULL,
    naics_code INT REFERENCES naics_codes(naics_code),
    supply_chain_position TEXT,
    trl INT,
    potential_applications TEXT
);

-- Create Companies Table (Placeholder)
CREATE TABLE companies (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    naics_code INT REFERENCES naics_codes(naics_code)
);

-- Create Technology-Companies Relationship Table
CREATE TABLE technology_companies (
    technology_id INT REFERENCES technologies(id),
    company_id INT REFERENCES companies(id),
    PRIMARY KEY (technology_id, company_id)
);

-- Insert NAICS Codes
INSERT INTO naics_codes (naics_code, description) VALUES (518210.0, 'Data Processing, Hosting, and Related Services');
INSERT INTO naics_codes (naics_code, description) VALUES (334220.0, 'Radio and Wireless Communications Equipment Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (334413.0, 'Semiconductor and Related Device Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (541715.0, 'Research and Development in Physical, Engineering, and Life Sciences');
INSERT INTO naics_codes (naics_code, description) VALUES (541713.0, 'Nanotechnology Research and Development');
INSERT INTO naics_codes (naics_code, description) VALUES (541715.0, 'Research and Development in AI');
INSERT INTO naics_codes (naics_code, description) VALUES (511210.0, 'Software Publishers');
INSERT INTO naics_codes (naics_code, description) VALUES (523920.0, 'Portfolio Management');
INSERT INTO naics_codes (naics_code, description) VALUES (331110.0, 'Iron and Steel Mills and Ferroalloy Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (325211.0, 'Plastics Material and Resin Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (334419.0, 'Other Electronic Component Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (336412.0, 'Aircraft Engine and Engine Parts Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (333611.0, 'Turbine and Turbine Generator Set Units Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (334516.0, 'Analytical Laboratory Instrument Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (334511.0, 'Search, Detection, Navigation, and Guidance Instrument Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (333248.0, 'Industrial Additive Manufacturing Machinery Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (333517.0, 'Machine Tool Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (325998.0, 'All Other Miscellaneous Chemical Product and Preparation Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (541512.0, 'Computer Systems Design Services');
INSERT INTO naics_codes (naics_code, description) VALUES (621511.0, 'Medical Laboratories');
INSERT INTO naics_codes (naics_code, description) VALUES (541715.0, 'Research and Development in Biotechnology');
INSERT INTO naics_codes (naics_code, description) VALUES (325412.0, 'Pharmaceutical Preparation Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (541714.0, 'Research and Development in Biotechnology (except Nanobiotechnology)');
INSERT INTO naics_codes (naics_code, description) VALUES (334510.0, 'Electromedical and Electrotherapeutic Apparatus Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (335911.0, 'Storage Battery Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (325120.0, 'Industrial Gas Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (221118.0, 'Other Electric Power Generation');
INSERT INTO naics_codes (naics_code, description) VALUES (334519.0, 'Other Measuring and Controlling Device Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (221116.0, 'Geothermal Electric Power Generation');
INSERT INTO naics_codes (naics_code, description) VALUES (541519.0, 'Other Computer Related Services');
INSERT INTO naics_codes (naics_code, description) VALUES (517311.0, 'Wired Telecommunications Carriers');
INSERT INTO naics_codes (naics_code, description) VALUES (517919.0, 'All Other Telecommunications');
INSERT INTO naics_codes (naics_code, description) VALUES (334517.0, 'Irradiation Apparatus Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (336414.0, 'Guided Missile and Space Vehicle Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (336411.0, 'Aircraft Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (336992.0, 'Military Armored Vehicle, Tank, and Tank Component Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (336111.0, 'Automobile Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (336612.0, 'Boat Building');
INSERT INTO naics_codes (naics_code, description) VALUES (339113.0, 'Surgical Appliance and Supplies Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (339920.0, 'Sporting and Athletic Goods Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (334310.0, 'Audio and Video Equipment Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (334210.0, 'Telephone Apparatus Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (334111.0, 'Electronic Computer Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (334412.0, 'Bare Printed Circuit Board Manufacturing');
INSERT INTO naics_codes (naics_code, description) VALUES (336415.0, 'Spacecraft Propulsion Units Manufacturing');

-- Insert Technologies
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'High-performance computing', 518210.0, 'ASI', TRL 9, 'Scientific Computing, Cloud Supercomputing, Climate Simulation, Drug Discovery, AI/ML Workloads, Financial Modeling, Algorithmic Trading, HPC for Algorithmic Trading, Risk Analysis, Market Forecasting');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'Edge computing', 334220.0, 'EUP', TRL 8, 'Smart IoT Devices, Wearables, Real-time Analytics, Smart Factories, Predictive Maintenance, Autonomous Robotics, Real-time AI Analytics for Cybersecurity, Connected Vehicles, Defense Applications');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'Advanced architectures', 334413.0, 'CET', TRL 4, 'Quantum Cryptography, Quantum Simulation for Drug Discovery, Fault-Tolerant Qubits');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'Advanced architectures', 541715.0, 'CET', TRL 3, 'AI-Specific Accelerators (TPUs, GPUs, ASICs), Low-Power AI Chips');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'Advanced architectures', 541713.0, 'CET', TRL 3, 'Quantum Dots, Memristors, Next-Gen AI Chips');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'Cloud computing', 518210.0, 'ASI', TRL 9, 'Enterprise SaaS, Hybrid Cloud, Distributed Cloud Infrastructure, Cloud Security, Confidential Computing & Secure Enclaves');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'AI applications', 541715.0, 'ASI', TRL 8, 'Chatbots, Large Language Models (LLMs), AI-Powered Assistants');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'AI applications', 541715.0, 'ASI', TRL 8, 'Facial Recognition, Autonomous Vehicles, Medical Imaging');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'AI applications', 541715.0, 'ASI', TRL 8, 'Financial Forecasting, Supply Chain Optimization, Customer Behavior Analysis');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'AI applications', 511210.0, 'ASI', TRL 8, 'Threat Detection, Anomaly Detection, AI-Powered Intrusion Prevention');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'AI applications', 541715.0, 'ASI', TRL 8, 'AI for Drug Discovery, Personalized Medicine, Bioinformatics, Smart Grids, AI-Driven Carbon Capture, Renewable Energy Forecasting, AI for Intelligence Analysis, Surveillance, Autonomous Military Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Computing', 'AI applications', 523920.0, 'ASI', TRL 8, 'Fraud Detection, Algorithmic Trading, Credit Risk Analysis');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Engineering Materials', 'Nanomaterials', 541713.0, 'RMC', TRL 4, 'Graphene for Electronics, Graphene-Based Composites, Energy Storage Applications');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Engineering Materials', 'Nanomaterials', 541713.0, 'RMC', TRL 5, 'Structural Reinforcement, Conductive Composites, Biomedical Applications');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Engineering Materials', 'Smart Materials', 541715.0, 'ASI', TRL 7, 'Aerospace Components, Biomedical Devices, Actuators');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Engineering Materials', 'Smart Materials', 541715.0, 'ASI', TRL 6, 'Protective Coatings, Aerospace Structures, Medical Implants');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Engineering Materials', 'High-Entropy Alloys', 331110.0, 'MF', TRL 6, 'Lightweight Aerospace Materials, High-Strength Structural Components, Corrosion-Resistant Coatings');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Engineering Materials', 'Metamaterials', 541713.0, 'RMC', TRL 3, 'Electromagnetic Wave Manipulation, Cloaking Devices, Advanced Lenses, RF Shielding');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Engineering Materials', 'Biodegradable Materials', 325211.0, 'MF', TRL 7, 'Eco-Friendly Packaging, Medical Implants, Sustainable Construction Materials');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Engineering Materials', 'Superconducting Materials', 334419.0, 'CET', TRL 5, 'Quantum Computing Components, Power Transmission Systems, Magnetic Levitation');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Gas Turbine Engines', 'Aircraft Engines', 336412.0, 'ASI', TRL 7, 'High-Bypass Ratio Engines, Fuel-Efficient Jet Engines, Hybrid-Electric Propulsion Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Gas Turbine Engines', 'Aircraft Engines', 336412.0, 'MF', TRL 6, 'Nickel-Based Superalloys, Ceramic Matrix Composites, High-Temperature Resistant Coatings');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Gas Turbine Engines', 'Power Generation', 333611.0, 'ASI', TRL 8, 'Distributed Energy Systems, Backup Power for Grid Resilience, Hybrid Energy Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Gas Turbine Engines', 'Power Generation', 333611.0, 'ASI', TRL 7, 'Decarbonization of Power Generation, Low-Emission Turbines, Hydrogen Fuel Integration');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced and Networked Sensing', 'Photonics', 334516.0, 'ASI', TRL 8, 'Autonomous Vehicles, Geospatial Mapping, Environmental Monitoring');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced and Networked Sensing', 'Photonics', 334516.0, 'ASI', TRL 7, 'Thermal Imaging, Security Surveillance, Night Vision Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced and Networked Sensing', 'RF Sensing', 334220.0, 'ASI', TRL 8, 'Air Traffic Control, Defense Systems, Weather Monitoring');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced and Networked Sensing', 'RF Sensing', 334220.0, 'ASI', TRL 7, 'Electronic Warfare, Spectrum Analysis, Signal Intelligence (SIGINT)');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced and Networked Sensing', 'Quantum Sensing', 541715.0, 'CET', TRL 4, 'Quantum Magnetometers, Quantum Gravimeters, High-Precision Positioning');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced and Networked Sensing', 'Acoustic Sensing', 334511.0, 'ASI', TRL 6, 'Sonar Systems, Underwater Surveillance, Seismic Monitoring');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced and Networked Sensing', 'Biosensors', 334516.0, 'EUP', TRL 8, 'Medical Diagnostics, Environmental Detection, Wearable Health Sensors');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Manufacturing', 'Additive Manufacturing', 333248.0, 'MF', TRL 8, 'Lightweight Aircraft Components, Engine Parts, Structural Optimization');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Manufacturing', 'Additive Manufacturing', 333248.0, 'MF', TRL 6, 'Tissue Engineering, Organ Printing, Medical Implants');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Manufacturing', 'Automation', 333517.0, 'ASI', TRL 7, 'Predictive Maintenance, Smart Factories, Robotics Integration');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Manufacturing', 'Nanomanufacturing', 541713.0, 'MF', TRL 5, 'Precision Nano-Scale Production, Advanced Coatings, Miniaturized Sensors');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Manufacturing', 'Digital Twin Manufacturing', 541715.0, 'ASI', TRL 7, 'Virtual Testing, Predictive Maintenance, Industrial Process Optimization');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Advanced Manufacturing', 'Sustainable Manufacturing', 325998.0, 'ASI', TRL 7, 'Green Materials Processing, Waste Reduction Technologies, Circular Economy Practices');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'Machine Learning', 541715.0, 'CET', TRL 5, 'Neural Networks, AI Model Training, Large-Scale Data Processing');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'Machine Learning', 541715.0, 'ASI', TRL 6, 'Privacy-Preserving AI, Decentralized AI Models, Edge AI');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'Computer Vision', 541715.0, 'ASI', TRL 7, 'Self-Driving Cars, Drone Navigation, Industrial Automation');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'Natural Language Processing', 541715.0, 'EUP', TRL 8, 'Chatbots, Virtual Assistants, AI-Driven Customer Service');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'Generative AI', 511210.0, 'ASI', TRL 7, 'Text Generation, AI Code Assistants, AI-Driven Research Tools');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'AI for Cybersecurity', 541512.0, 'ASI', TRL 8, 'Threat Detection, Anomaly Detection, AI-Powered Intrusion Prevention');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'AI for Healthcare', 621511.0, 'ASI', TRL 8, 'Medical Imaging, AI-Assisted Diagnosis, Drug Discovery');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'AI for Finance', 523920.0, 'ASI', TRL 8, 'Fraud Detection, Algorithmic Trading, Risk Analysis');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Artificial Intelligence', 'Explainable AI (XAI)', 541715.0, 'ASI', TRL 6, 'AI Model Interpretability, Bias Detection, Fair AI Practices');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Biotechnologies', 'Synthetic Biology', 541715.0, 'CET', TRL 5, 'CRISPR, Gene Therapy, Genomic Engineering');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Biotechnologies', 'Synthetic Biology', 541715.0, 'MF', TRL 7, 'Engineered Microbes, Biofuels, Biopolymers');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Biotechnologies', 'Biopharmaceuticals', 325412.0, 'EUP', TRL 8, 'Immunotherapy, Targeted Cancer Treatments, Biosimilars');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Biotechnologies', 'Biopharmaceuticals', 325412.0, 'EUP', TRL 8, 'mRNA Vaccines, RNA-Based Therapeutics, Personalized Medicine');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Biotechnologies', 'Bioinformatics', 541714.0, 'ASI', TRL 6, 'Genomic Data Analysis, AI for Drug Discovery, Personalized Medicine');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Biotechnologies', 'Biomedical Engineering', 334510.0, 'ASI', TRL 7, 'Wearable Medical Devices, Implantable Sensors, AI-Assisted Surgery');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Biotechnologies', 'Agricultural Biotechnology', 541715.0, 'ASI', TRL 7, 'Genetically Modified Crops, Precision Agriculture, Livestock Genomics');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Advanced Solar Technologies', 334413.0, 'CET', TRL 6, 'High-Efficiency Solar Panels, Flexible Solar Films, Space-Based Solar Power');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Advanced Solar Technologies', 334413.0, 'ASI', TRL 8, 'Increased Energy Yield, Dual-Sided Light Absorption, Smart Solar Farms');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Next-Generation Batteries', 335911.0, 'MF', TRL 7, 'Higher Energy Density, Improved Safety, EV and Grid Storage');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Next-Generation Batteries', 335911.0, 'MF', TRL 7, 'Long-Duration Grid Storage, Renewable Energy Integration, Industrial Backup Power');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Hydrogen Technologies', 325120.0, 'ASI', TRL 7, 'Electrolysis-Based Hydrogen, Renewable Hydrogen Fuel, Hydrogen for Industrial Applications');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Hydrogen Technologies', 325120.0, 'ASI', TRL 8, 'Fuel Cell Vehicles, Stationary Power, Hydrogen-Powered Aircraft');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Grid Modernization', 221118.0, 'EUP', TRL 8, 'Real-Time Grid Optimization, AI for Energy Management, Demand Response Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Grid Modernization', 334519.0, 'EUP', TRL 8, 'Smart Meters, Energy Consumption Analytics, Automated Demand Response');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Wind Energy Innovations', 333611.0, 'ASI', TRL 7, 'Deep-Sea Wind Farms, Energy Production in Remote Areas, High-Capacity Wind Power');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Wind Energy Innovations', 333611.0, 'ASI', TRL 7, 'Urban Wind Energy, Distributed Energy Systems, Low-Turbulence Power Generation');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Nuclear Fusion', 541715.0, 'CET', TRL 3, 'Tokamak Reactors, Stellarators, Magnetized Target Fusion, Laser-Induced Fusion');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Clean Energy', 'Geothermal Energy Innovations', 221116.0, 'ASI', TRL 8, 'Enhanced Geothermal Systems (EGS), Geothermal Heat Pumps, Deep Earth Drilling Technologies');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Cybersecurity & Data Privacy', 'Threat Detection & Response', 541512.0, 'ASI', TRL 8, 'Real-Time Threat Analysis, Behavioral Anomaly Detection, AI-Powered Intrusion Prevention');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Cybersecurity & Data Privacy', 'Threat Detection & Response', 541512.0, 'ASI', TRL 7, 'Identity Verification, Least Privilege Access Control, Continuous Authentication');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Cybersecurity & Data Privacy', 'Encryption & Data Protection', 541519.0, 'CET', TRL 4, 'Quantum-Resistant Encryption, Secure Communication Protocols, Cryptographic Key Management');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Cybersecurity & Data Privacy', 'Encryption & Data Protection', 541519.0, 'ASI', TRL 6, 'Encrypted Data Processing, Secure Data Sharing, Cloud Security');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Cybersecurity & Data Privacy', 'Secure Networks & Infrastructure', 517311.0, 'ASI', TRL 7, 'Secure 5G Networks, IoT Security, Next-Generation Network Encryption');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Cybersecurity & Data Privacy', 'Secure Networks & Infrastructure', 517919.0, 'ASI', TRL 7, 'Secure Satellite Communications, Space-Based Data Protection, Cyber Threat Detection in Space');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Cybersecurity & Data Privacy', 'Privacy-Preserving Technologies', 541715.0, 'ASI', TRL 6, 'Federated Learning, Differential Privacy, AI for Data Anonymization');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Cybersecurity & Data Privacy', 'Identity & Access Management', 541512.0, 'EUP', TRL 8, 'Biometric Authentication, Multi-Factor Authentication (MFA), Blockchain for Identity Management');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Directed Energy', 'High-Power Lasers', 334517.0, 'ASI', TRL 8, 'Missile Defense, Anti-Drone Systems, Battlefield Lasers');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Directed Energy', 'High-Power Lasers', 334517.0, 'CET', TRL 7, 'Precision Machining, Satellite-Based Laser Communication, Space Debris Removal');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Directed Energy', 'High-Power Microwaves', 334220.0, 'ASI', TRL 7, 'Electronic Warfare, Disabling Enemy Electronics, Cyber-Physical Attacks');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Directed Energy', 'High-Power Microwaves', 334220.0, 'EUP', TRL 8, 'Active Denial Systems, Riot Control, Perimeter Defense');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Directed Energy', 'Particle Beam Weapons', 541715.0, 'CET', TRL 4, 'High-Energy Particle Beams, Advanced Radiation-Based Weaponry, Space Defense Applications');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Directed Energy', 'Electromagnetic Railguns', 336414.0, 'ASI', TRL 6, 'Kinetic Energy Weapons, Hypersonic Projectile Launch Systems, Naval Defense Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Autonomous & Uncrewed Systems', 'Aerial Systems', 336411.0, 'ASI', TRL 9, 'Drone Surveillance, Delivery Drones, Military Reconnaissance');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Autonomous & Uncrewed Systems', 'Aerial Systems', 336411.0, 'ASI', TRL 7, 'Cooperative Drone Operations, Disaster Response, Battlefield Coordination');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Autonomous & Uncrewed Systems', 'Ground Systems', 336992.0, 'ASI', TRL 8, 'Unmanned Military Vehicles, AI-Driven Battlefield Robotics, Uncrewed Logistics Support');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Autonomous & Uncrewed Systems', 'Ground Systems', 336111.0, 'EUP', TRL 8, 'Autonomous Transportation, Ride-Sharing AI, AI-Based Fleet Management');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Autonomous & Uncrewed Systems', 'Maritime Systems', 336612.0, 'ASI', TRL 7, 'Submarine Surveillance, Oceanographic Exploration, Mine Detection');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Autonomous & Uncrewed Systems', 'Maritime Systems', 336612.0, 'ASI', TRL 7, 'Autonomous Naval Patrols, Ocean Cargo Transport, Anti-Piracy Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Autonomous & Uncrewed Systems', 'Space Systems', 336414.0, 'ASI', TRL 8, 'Self-Healing Spacecraft, AI-Optimized Orbital Maneuvering, Deep Space Exploration');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Autonomous & Uncrewed Systems', 'Space Systems', 336414.0, 'EUP', TRL 7, 'Autonomous Satellite Repair, Space Debris Removal, Orbital Fuel Depots');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Human-Machine Interfaces', 'Brain-Computer Interfaces (BCI)', 334510.0, 'ASI', TRL 6, 'Neural Signal Processing, Mind-Controlled Prosthetics, Neurorehabilitation Devices');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Human-Machine Interfaces', 'Brain-Computer Interfaces (BCI)', 334510.0, 'EUP', TRL 8, 'Direct Brain-to-Computer Communication, AI-Augmented Cognition, Neural Implants');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Human-Machine Interfaces', 'Haptic Interfaces', 339113.0, 'ASI', TRL 7, 'Virtual Reality (VR) Feedback, Remote Surgery, Advanced Prosthetics');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Human-Machine Interfaces', 'Haptic Interfaces', 339920.0, 'EUP', TRL 8, 'Gaming Haptics, Robotics Control, Enhanced Training Simulations');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Human-Machine Interfaces', 'Augmented Reality (AR) & Virtual Reality (VR)', 334310.0, 'ASI', TRL 7, 'Immersive Training, Heads-Up Displays, Industrial Maintenance Assistance');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Human-Machine Interfaces', 'Augmented Reality (AR) & Virtual Reality (VR)', 334310.0, 'ASI', TRL 8, 'Virtual Training Environments, Medical Simulations, Next-Gen Gaming');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Human-Machine Interfaces', 'Wearable Interfaces', 334519.0, 'ASI', TRL 7, 'Smart Watches, EEG Headbands, Biometric Wearables');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Human-Machine Interfaces', 'Exoskeletons & Assistive Devices', 334510.0, 'EUP', TRL 8, 'Rehabilitation Robotics, Military Load Assistance, Industrial Worker Support');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Hypersonics', 'Hypersonic Vehicles', 336414.0, 'ASI', TRL 7, 'High-Speed Maneuverable Weapons, Strategic Deterrence, Orbital Reentry Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Hypersonics', 'Hypersonic Vehicles', 336414.0, 'ASI', TRL 7, 'Precision Strike, Long-Range Tactical Engagements, Anti-Ship Capabilities');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Hypersonics', 'Hypersonic Vehicles', 541715.0, 'ASI', TRL 6, 'Orbital Hypersonic Maneuvering, Space-Based Strike Capabilities');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Hypersonics', 'Hypersonic Vehicles', 336412.0, 'ASI', TRL 6, 'Next-Gen Aerospace Transport, Ultra-Fast Global Delivery');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Hypersonics', 'Propulsion Systems', 336412.0, 'MF', TRL 6, 'Air-Breathing Hypersonic Propulsion, Rapid Global Strike, Next-Gen Aerospace Transport');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Hypersonics', 'Propulsion Systems', 336412.0, 'MF', TRL 6, 'High-Speed Air-Breathing Engines, Hybrid Rocket Propulsion, Advanced Military Jet Propulsion');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Hypersonics', 'Hypersonic Materials', 541713.0, 'MF', TRL 7, 'Thermal Protection Systems, Ultra-High-Temperature Ceramics, Hypersonic Heat Shields');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Hypersonics', 'Test & Evaluation Technologies', 541715.0, 'ASI', TRL 8, 'Wind Tunnel Testing, Computational Fluid Dynamics (CFD) Simulations, High-Speed Flight Experimentation');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Next-Gen Wireless Networks', 517311.0, 'ASI', TRL 6, 'Ultra-High-Speed Connectivity, AI-Optimized Networks, Holographic Communications');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Next-Gen Wireless Networks', 517311.0, 'ASI', TRL 8, 'Global Broadband Coverage, Resilient Communications, Military Tactical Networks');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Next-Gen Wireless Networks', 541512.0, 'EUP', TRL 7, 'Autonomous Network Management, Self-Healing Networks, AI-Based Traffic Routing');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Quantum Communications', 541715.0, 'CET', TRL 4, 'Unbreakable Encryption, Secure Government Communications, Banking Security');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Quantum Communications', 541715.0, 'CET', TRL 4, 'Quantum Data Transmission, Entanglement-Based Networking, Secure Cloud Computing');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Optical Networking', 334210.0, 'ASI', TRL 7, 'Laser-Based Data Transmission, High-Speed Satellite Links, Secure Optical Communications');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Optical Networking', 334210.0, 'ASI', TRL 7, 'Next-Gen Fiber Optic Cables, AI-Enhanced Network Routing, Data Center Connectivity');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Secure Communications', 517919.0, 'EUP', TRL 8, 'End-to-End Encrypted Messaging, Military-Grade Secure Networks, AI-Based Cyber Defense');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Edge Computing & IoT Networks', 541512.0, 'ASI', TRL 7, 'Edge AI Processing, Low-Latency IoT Networks, Real-Time Industrial Automation');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Mesh & Ad Hoc Networks', 517919.0, 'ASI', TRL 7, 'Disaster Recovery Communications, Battlefield Connectivity, Sensor Networks');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Communications & Networking', 'Space Communications', 541715.0, 'ASI', TRL 6, 'Deep-Space Delay-Tolerant Networking (DTN), Mars & Lunar Communications');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Positioning, Navigation & Timing', 'Global Navigation Satellite Systems (GNSS)', 334220.0, 'ASI', TRL 8, 'GPS Modernization, Multi-Constellation Receivers, Anti-Jamming Technologies');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Positioning, Navigation & Timing', 'Global Navigation Satellite Systems (GNSS)', 334220.0, 'ASI', TRL 7, 'Alternative PNT Solutions, GNSS Spoofing Protection, Encrypted Military Signals');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Positioning, Navigation & Timing', 'Inertial Navigation Systems (INS)', 334511.0, 'CET', TRL 4, 'GPS-Denied Navigation, Ultra-Precise Positioning, Defense-Grade Navigation Solutions');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Positioning, Navigation & Timing', 'Inertial Navigation Systems (INS)', 334511.0, 'EUP', TRL 7, 'Autonomous Vehicle Navigation, AI-Powered Sensor Fusion, Maritime and Aerial Navigation');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Positioning, Navigation & Timing', 'Atomic Clocks & Timing Systems', 334519.0, 'ASI', TRL 7, 'Ultra-Precise Timing for GNSS, Secure Communications, Network Synchronization');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Positioning, Navigation & Timing', 'Atomic Clocks & Timing Systems', 334519.0, 'CET', TRL 4, 'Quantum-Based Atomic Clocks, High-Stability Frequency Standards, Secure Financial Transactions');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Positioning, Navigation & Timing', 'Alternative PNT Technologies', 541715.0, 'ASI', TRL 7, 'Earth-Based Radio Navigation, Celestial Navigation, Magnetic Navigation Systems');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Quantum Technologies', 'Quantum Computing', 334111.0, 'CET', TRL 4, 'Fault-Tolerant Quantum Processors, Quantum Cloud Computing, AI-Enhanced Quantum Algorithms');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Quantum Technologies', 'Quantum Computing', 334111.0, 'CET', TRL 4, 'Precision Quantum Processing, Scalable Quantum Systems, Secure Quantum Cryptography');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Quantum Technologies', 'Quantum Sensing', 541715.0, 'CET', TRL 4, 'Medical Imaging, Mineral Exploration, Military Submarine Detection');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Quantum Technologies', 'Quantum Sensing', 541715.0, 'CET', TRL 4, 'Gravitational Mapping, Underground Infrastructure Detection, Earthquake Prediction');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Quantum Technologies', 'Quantum Communications', 541715.0, 'CET', TRL 4, 'Unbreakable Encryption, Secure Government & Financial Transactions, Data Security');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Quantum Technologies', 'Quantum Communications', 541715.0, 'CET', TRL 3, 'Ultra-Secure Data Transmission, Quantum-Entangled Networks, Deep-Space Quantum Links');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Quantum Technologies', 'Quantum Materials', 541713.0, 'MF', TRL 5, 'Topological Qubits, Quantum Dots, Superconducting Materials for Quantum Hardware');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Semiconductors & Microelectronics', 'Advanced Semiconductor Manufacturing', 334413.0, 'MF', TRL 6, 'Next-Generation Process Nodes, AI-Optimized Chip Design, Ultra-Efficient Computing');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Semiconductors & Microelectronics', 'Advanced Semiconductor Manufacturing', 334413.0, 'MF', TRL 7, 'High-Density Memory, Improved Power Efficiency, AI Accelerator Chips');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Semiconductors & Microelectronics', 'Wide Bandgap Semiconductors', 334413.0, 'MF', TRL 7, 'High-Efficiency Power Electronics, RF Amplifiers, Electric Vehicles');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Semiconductors & Microelectronics', 'Wide Bandgap Semiconductors', 334413.0, 'MF', TRL 7, 'Electric Vehicle Powertrains, Industrial Power Supplies, High-Frequency Switching');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Semiconductors & Microelectronics', 'Microelectromechanical Systems (MEMS)', 334419.0, 'ASI', TRL 8, 'MEMS Sensors, Actuators, RF MEMS for 5G and IoT, Biomedical Sensors');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Semiconductors & Microelectronics', 'Advanced Packaging Technologies', 334412.0, 'MF', TRL 7, 'Chiplet Architectures, Heterogeneous Integration, Fan-Out Wafer-Level Packaging');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Semiconductors & Microelectronics', 'Neuromorphic & AI Chips', 334413.0, 'EUP', TRL 7, 'Brain-Inspired Computing, AI-Specific Hardware Accelerators, Edge AI Processors');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Space Technologies', 'Launch Systems', 336414.0, 'ASI', TRL 8, 'Cost-Effective Space Access, Rapid Launch Cadence, Commercial Spaceflight');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Space Technologies', 'Launch Systems', 336414.0, 'ASI', TRL 7, 'Point-to-Point Space Travel, Military Reconnaissance, Next-Gen Orbital Delivery');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Space Technologies', 'Satellite Technologies', 334220.0, 'ASI', TRL 8, 'Global Internet Coverage, Earth Observation, IoT Connectivity');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Space Technologies', 'Satellite Technologies', 334220.0, 'ASI', TRL 7, 'All-Weather Earth Observation, Military Surveillance, Disaster Monitoring');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Space Technologies', 'Space Propulsion', 336415.0, 'MF', TRL 6, 'Deep-Space Missions, Satellite Station Keeping, Fuel-Efficient Space Travel');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Space Technologies', 'Space Propulsion', 336415.0, 'CET', TRL 5, 'Rapid Interplanetary Travel, Mars Missions, High-Thrust Space Maneuvering');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Space Technologies', 'Space Habitats & Infrastructure', 541715.0, 'ASI', TRL 6, 'Orbital Space Stations, Lunar & Martian Habitats, Space-Based Manufacturing');
INSERT INTO technologies (category, subcategory, naics_code, supply_chain_position, trl, potential_applications) VALUES ('Space Technologies', 'On-Orbit Servicing & Debris Mitigation', 541715.0, 'ASI', TRL 7, 'Satellite Refueling, Space Debris Removal, Robotic On-Orbit Repairs');
